services:
  - type: web
    name: smartapp-web
    env: docker
    plan: starter
    dockerfilePath: ./dockerfile
    autoDeploy: true
    healthCheckPath: /health.php
    scaling:
      minInstances: 1
      maxInstances: 3
    envVars:
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: smartapp-db
          property: host
      - key: DB_USERNAME
        fromDatabase:
          name: smartapp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: smartapp-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: smartapp-db
          property: database
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: ${SMTP_USERNAME}
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
      - key: SMTP_FROM_EMAIL
        value: ${SMTP_FROM_EMAIL}
      - key: SMTP_FROM_NAME
        value: SmartApp
      - key: DEPLOYMENT_ENV
        value: production

  - type: pserv
    name: smartapp-db
    plan: free
    env: postgresql
    autoDeploy: true
    envVars:
      - key: POSTGRES_DB
        value: members_system
      - key: POSTGRES_USER
        value: smartapp_user
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
