services:
  - type: web
    name: smartapp-web
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: SMTP_HOST
        value: ${SMTP_HOST}
      - key: SMTP_PORT
        value: ${SMTP_PORT}
      - key: SMTP_USERNAME
        value: ${SMTP_USERNAME}
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
      - key: SMTP_FROM_EMAIL
        value: ${SMTP_FROM_EMAIL}
      - key: SMTP_FROM_NAME
        value: ${SMTP_FROM_NAME}

  - type: pserv
    name: smartapp-mysql-db
    plan: free
    env: mysql
    envVars:
      - key: MYSQL_DATABASE
        value: members_system
      - key: MYSQL_USER
        value: smartapp_user
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}
